#! /usr/bin/Rscript
args<-commandArgs(T)

if (length(args)==0) {message("Please enter an extended-fasta input file annotated with ecotag.")} else
{  
  filefasta <- args[1] #Must be a fasta file (from obitab) 
  if (length(args)<2) outfile <-paste(filefasta,".annotated.csv",sep="") else outfile  <- args[2]   

suppressPackageStartupMessages(library("Biostrings"))
length_id <- 14

dir_taxo <- "~/taxo_dec2015/"
taxo_names <- read.table(paste(dir_taxo,"order.complete.csv",sep=""),sep=",",head=T) 
class_to_sk <- unique(taxo_names[,2:5])
phylum_to_sk <- unique(class_to_sk[,2:4])
kingdom_to_sk <-unique(phylum_to_sk[,2:3]) 
showlines <- 100

family_to_order <- read.table(paste(dir_taxo,"family_to_order.csv",sep=""),sep=",",head=T)
genus_to_family <- read.table(paste(dir_taxo,"genus_to_family.csv",sep=""),sep=",",head=T)

get_rank <- function(cadena){
  if (gregexpr("rank=",cadena)[[1]]>0) 
    {cadena <- substr(cadena,gregexpr("rank=",cadena)[[1]]+5,nchar(cadena))
    cadena <- substr(cadena,1,regexpr(";",cadena)[[1]]-1)
  }  else cadena <- "None"
  return(cadena)
}

exceptions <- c("Bacillariophycidae","Bilateria","Collembola","Chelicerata","Crustacea","Deuterostomia","Ecdysozoa",
                "Eleutherozoa","Echinozoa","Asterozoa","Endopterygota","Eumalacostraca","Eumetazoa","Eurotiomycetidae","Euteleostomi",
                "Euthyneura","Hydroidolina","hypocreomyceta","Hypocreomycetidae","Hypsogastropoda","leotiomyceta","Leotiomycetidae","Lophotrochozoa",
                "Myxogastria","Neocopepoda","Podoplea","Neoptera","Octocorallia","Hexacorallia","Scleractinia","Opisthokonta","Panarthropoda",
                "Pancrustacea","Peracarida","Protostomia","PX clade","Rhodophyta","Sarcoptiformes","Scolecida","Aciculata","Palpata",
                "sordariomyceta","Sordariomycetidae","Stramenopiles","Stylommatophora","Trombidiformes",
                "Pterygota","Paleoptera","Nudipleura","Panpulmonata","Heterobranchia","Caenogastropoda","Eucarida","Hoplocarida",
                "Streptophytina","Entomobryomorpha","Poduromorpha","Symphypleona","Fungi incertae sedis","Haptophyceae","Jakobida","Alveolata",
                "Palaeonemertea","Euopisthobranchia","Euteleosteomorpha","Littorinimorpha","Littorinoidea","Fragilariophycidae","Mandibulata",
                "Actinopterygii","Batoidea","Boreoeutheria","Cephalaspidea","Clitellata","Clupeocephala","Decapodiformes","Echinacea","Euechinoidea",
                "Embryophyta","Eupercaria","Percomorphaceae","Ophiuridea","Patellogastropoda","Piroplasmida","Pteriomorphia","Synurophyceae","Vetigastropoda",
                "Cirripedia","Dikarya","Euacanthomorphacea","Galeoidea","Gnathostomata","Intramacronucleata","Neogastropoda","Phascolosomatidea","Trachylinae"

)

fix_exceptions <- function(scientific_name){
  if (scientific_name == "Jakobida") {
    matrix.data["order_name",2] <- "Jakobida"
    matrix.data["class_name",2] <- "Jakobea"
    matrix.data["phylum_name",2] <- "Loukozoa"
    matrix.data["kingdom_name",2] <- "Loukozoa"
    matrix.data["superkingdom_name",2] <- "Excavata"
  }
  if (scientific_name == "Piroplasmida") {
    matrix.data["order_name",2] <- "Piroplasmorida"
    matrix.data["class_name",2] <- "Aconoidasida"
    matrix.data["phylum_name",2] <- "Apicomplexa"
    matrix.data["kingdom_name",2] <- "Alveolata"
    matrix.data["superkingdom_name",2] <- "Chromalveolata"
  }
  if (scientific_name == "Intramacronucleata") {
    matrix.data["class_name",2] <- "Intramacronucleata"
    matrix.data["phylum_name",2] <- "Ciliophora"
    matrix.data["kingdom_name",2] <- "Alveolata"
    matrix.data["superkingdom_name",2] <- "Chromalveolata"
  }

  if (scientific_name == "Palaeonemertea") {
    matrix.data["order_name",2] <- "Palaeonemertea"
    matrix.data["class_name",2] <- "Anopla"
    matrix.data["phylum_name",2] <- "Nemertea"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
    matrix.data["rank",2] <- "order"
  }
  if (scientific_name %in%  c("Phascolosomatidea")) {
    matrix.data["order_name",2] <- "Phascolosomatiformes"
    matrix.data["class_name",2] <- "Sipuncula"
    matrix.data["phylum_name",2] <- "Annelida"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }


  if (scientific_name == "Alveolata") {
    matrix.data["class_name",2] <- "None"
    matrix.data["phylum_name",2] <- "None"
    matrix.data["kingdom_name",2] <- "Alveolata"
    matrix.data["superkingdom_name",2] <- "Chromalveolata"
    matrix.data["rank",2] <- "kingdom"
  }
  if (scientific_name == "Haptophyceae") {
    matrix.data["class_name",2] <- "Haptophyceae"
    matrix.data["phylum_name",2] <- "Haptophyta"
    matrix.data["kingdom_name",2] <- "Hacrobia"
    matrix.data["superkingdom_name",2] <- "Chromalveolata"
    matrix.data["rank",2] <- "class"
  }
  if (scientific_name == "Synurophyceae") {
    matrix.data["class_name",2] <- "Chrysophyceae"
    matrix.data["phylum_name",2] <- "Ochrophyta"
    matrix.data["kingdom_name",2] <- "Stramenopiles"
    matrix.data["superkingdom_name",2] <- "Chromalveolata"
    matrix.data["rank",2] <- "class"
  }

  if (scientific_name %in% c("Fungi incertae sedis","Dykarya")) {
    matrix.data["class_name",2] <- "None"
    matrix.data["phylum_name",2] <- "None"
    matrix.data["kingdom_name",2] <- "Fungi"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
    matrix.data["rank",2] <- "kingdom"
  }
  if (scientific_name == "Opisthokonta") {
    matrix.data["class_name",2] <- "None"
    matrix.data["phylum_name",2] <- "None"
    matrix.data["kingdom_name",2] <- "None"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
    matrix.data["rank",2] <- "superkingdom"
  }
    if (scientific_name %in% c("Streptophytina","Embryophyta")) {
    matrix.data["class_name",2] <- "None"
    matrix.data["phylum_name",2] <- "Streptophyta"
    matrix.data["kingdom_name",2] <- "Viridiplantae"
    matrix.data["superkingdom_name",2] <- "Archaeplastida"
  }
  if (scientific_name %in% c("Bilateria","Ecdysozoa","Eumetazoa","Lophotrochozoa","Panarthropoda","Protostomia","Deuterostomia")) {
    matrix.data["class_name",2] <- "None"
    matrix.data["phylum_name",2] <- "None"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in% c("Scolecida","Aciculata","Palpata")) {
    matrix.data["class_name",2] <- "Polychaeta"
    matrix.data["phylum_name",2] <- "Annelida"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in% c("Clitellata")) {
    matrix.data["class_name",2] <- "Clitellata"
    matrix.data["phylum_name",2] <- "Annelida"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in% c("Eleutherozoa","Echinozoa","Asterozoa")) {
    matrix.data["class_name",2] <- "None"
    matrix.data["phylum_name",2] <- "Echinodermata"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in% c("Euechinoidea","Echinacea","Gnathostomata")) {
    matrix.data["class_name",2] <- "Echinoidea"
    matrix.data["phylum_name",2] <- "Echinodermata"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in% c("Ophiuridea")) {
    matrix.data["class_name",2] <- "Ophiuroidea"
    matrix.data["phylum_name",2] <- "Echinodermata"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  
  if (scientific_name == "Rhodophyta") {
    matrix.data["phylum_name",2] <- "Rhodophyta"
    matrix.data["kingdom_name",2] <- "Rhodophyta"
    matrix.data["superkingdom_name",2] <- "Archaeplastida"
    matrix.data["rank",2] <- "phylum"
  }
  if (scientific_name == "PX clade") {
    matrix.data["phylum_name",2] <- "Ochrophyta"
    matrix.data["kingdom_name",2] <- "Stramenopiles"
    matrix.data["superkingdom_name",2] <- "Chromalveolata"
    matrix.data["rank",2] <- "phylum"
  }
  if (scientific_name == "Stramenopiles") {
    matrix.data["kingdom_name",2] <- "Stramenopiles"
    matrix.data["superkingdom_name",2] <- "Chromalveolata"
    matrix.data["rank",2] <- "kingdom"
  }
  if (scientific_name %in% c("Euteleostomi","Euteleosteomorpha","Actinopterygii","Clupeocephala","Eupercaria","Percomorphaceae","Euacanthomorphacea")) {
    matrix.data["class_name",2] <- "Actinopterygii"
    matrix.data["phylum_name",2] <- "Chordata"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in% c("Batoidea","Galeoidea")) {
    matrix.data["class_name",2] <- "Chondrichthyes"
    matrix.data["phylum_name",2] <- "Chordata"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in% c("Boreoeutheria")) {
    matrix.data["class_name",2] <- "Mammalia"
    matrix.data["phylum_name",2] <- "Chordata"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  
    if (scientific_name %in% c("Chelicerata","Crustacea","Pancrustacea","Mandibulata")) {
    matrix.data["class_name",2] <- "None"
    matrix.data["phylum_name",2] <- "Arthropoda"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in% c("Eumalacostraca","Peracarida","Eucarida","Hoplocarida")) {
    matrix.data["class_name",2] <- "Malacostraca"
    matrix.data["phylum_name",2] <- "Arthropoda"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in% c("Neocopepoda","Podoplea","Cirripedia")) {
    matrix.data["class_name",2] <- "Maxillopoda"
    matrix.data["phylum_name",2] <- "Arthropoda"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in% c("Collembola","Entomobryomorpha","Poduromorpha","Symphypleona")) {
    matrix.data["order_name",2] <- "Collembola"
    matrix.data["class_name",2] <- "Hexapoda"
    matrix.data["phylum_name",2] <- "Arthropoda"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
    matrix.data["rank",2] <- "order"
  }
  if (scientific_name=="Sarcoptiformes") {
    matrix.data["order_name",2] <- "Sarcoptiformes"
    matrix.data["class_name",2] <- "Arachnida"
    matrix.data["phylum_name",2] <- "Arthropoda"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
    matrix.data["rank",2] <- "order"
  }
  if (scientific_name=="Trombidiformes") {
    matrix.data["order_name",2] <- "Trombidiformes"
    matrix.data["class_name",2] <- "Arachnida"
    matrix.data["phylum_name",2] <- "Arthropoda"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
    matrix.data["rank",2] <- "order"
  }
  if (scientific_name %in% c("Endopterygota","Neoptera","Pterygota","Paleoptera")) {
    matrix.data["class_name",2] <- "Insecta"
    matrix.data["phylum_name",2] <- "Arthropoda"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in% c("Stylommatophora","Euthyneura","Nudipleura","Panpulmonata","Heterobranchia",
                             "Euopisthobranchia","Hypsogastropoda","Caenogastropoda")) {
    matrix.data["class_name",2] <- "Gastropoda"
    matrix.data["phylum_name",2] <- "Mollusca"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in%  c("Littorinimorpha","Littorinoidea")) {
    matrix.data["order_name",2] <- "Littorinimorpha"
    matrix.data["class_name",2] <- "Gastropoda"
    matrix.data["phylum_name",2] <- "Mollusca"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in%  c("Patellogastropoda")) {
    matrix.data["order_name",2] <- "Patellogastropoda"
    matrix.data["class_name",2] <- "Gastropoda"
    matrix.data["phylum_name",2] <- "Mollusca"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in%  c("Vetigastropoda")) {
    matrix.data["order_name",2] <- "Vetigastropoda"
    matrix.data["class_name",2] <- "Gastropoda"
    matrix.data["phylum_name",2] <- "Mollusca"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in%  c("Neogastropoda")) {
    matrix.data["order_name",2] <- "Neogastropoda"
    matrix.data["class_name",2] <- "Gastropoda"
    matrix.data["phylum_name",2] <- "Mollusca"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }

  if (scientific_name %in%  c("Cephalaspidea")) {
    matrix.data["order_name",2] <- "Cephalaspidea"
    matrix.data["class_name",2] <- "Gastropoda"
    matrix.data["phylum_name",2] <- "Mollusca"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in%  c("Pteriomorphia")) {
    matrix.data["class_name",2] <- "Bivalvia"
    matrix.data["phylum_name",2] <- "Mollusca"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  
  if (scientific_name %in% c("Decapodiformes")) {
    matrix.data["class_name",2] <- "Cephalopoda"
    matrix.data["phylum_name",2] <- "Mollusca"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  
    if (scientific_name == "Myxogastria") {
    matrix.data["class_name",2] <- "Myxomycetes"
    matrix.data["phylum_name",2] <- "Mycetozoa"
    matrix.data["kingdom_name",2] <- "Conosa"
    matrix.data["superkingdom_name",2] <- "Amoebozoa"
    matrix.data["rank",2] <- "class"
    matrix.data["scientific_name",2] <- "Myxomycetes"
  }
  
  if (scientific_name == "Fragilariophycidae") {
    matrix.data["class_name",2] <- "Fragilariophyceae"
    matrix.data["phylum_name",2] <- "Bacillariophyta"
    matrix.data["kingdom_name",2] <- "Stramenopiles"
    matrix.data["superkingdom_name",2] <- "Chromalveolata"
    matrix.data["rank",2] <- "class"
    matrix.data["scientific_name",2] <- "Bacillariophyceae"
  }
  if (scientific_name == "Bacillariophycidae") {
    matrix.data["class_name",2] <- "Bacillariophyceae"
    matrix.data["phylum_name",2] <- "Bacillariophyta"
    matrix.data["kingdom_name",2] <- "Stramenopiles"
    matrix.data["superkingdom_name",2] <- "Chromalveolata"
    matrix.data["rank",2] <- "class"
    matrix.data["scientific_name",2] <- "Bacillariophyceae"
  }
  if (scientific_name %in% c("Octocorallia","Hexacorallia","Scleractinia")) {
    matrix.data["class_name",2] <- "Anthozoa"
    matrix.data["phylum_name",2] <- "Cnidaria"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in% c("Hydroidolina")) {
    matrix.data["class_name",2] <- "Hydrozoa"
    matrix.data["phylum_name",2] <- "Cnidaria"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }    
  if (scientific_name %in% c("Trachylinae")) {
    matrix.data["order_name",2] <- "Trachylina"
    matrix.data["class_name",2] <- "Hydrozoa"
    matrix.data["phylum_name",2] <- "Cnidaria"
    matrix.data["kingdom_name",2] <- "Metazoa"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }    

  if (scientific_name %in% c("sordariomyceta","Sordariomycetidae")) {
    matrix.data["class_name",2] <- "Sordariomycetes"
    matrix.data["phylum_name",2] <- "Ascomycota"
    matrix.data["kingdom_name",2] <- "Fungi"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in% c("leotiomyceta","Leotiomycetidae")) {
    matrix.data["class_name",2] <- "Leotiomycetes"
    matrix.data["phylum_name",2] <- "Ascomycota"
    matrix.data["kingdom_name",2] <- "Fungi"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
  if (scientific_name %in% c("eurotiomyceta","Eurotiomycetidae")) {
    matrix.data["class_name",2] <- "Eurotiomycetes"
    matrix.data["phylum_name",2] <- "Ascomycota"
    matrix.data["kingdom_name",2] <- "Fungi"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }  
  if (scientific_name %in% c("hypocreomyceta","Hypocreomycetidae")) {
    matrix.data["class_name",2] <- "Sordariomycetes"
    matrix.data["phylum_name",2] <- "Ascomycota"
    matrix.data["kingdom_name",2] <- "Fungi"
    matrix.data["superkingdom_name",2] <- "Opisthokonta"
  }
return(matrix.data)
}

#Read  fasta file
message("Reading ecotagged fasta file")
db <- readDNAStringSet(filefasta)
info <- db@ranges@NAMES
#Initialize 
inicio <- T 
message("Read ",length(db)," records")
for (fila in 1:length(db)) {
  infofasta <- info[fila]
  if (length(gregexpr("order_name",infofasta)[[1]])==2) infofasta <- sub(pattern="; order_name=",replacement="",x=infofasta)
  if (length(gregexpr("order=",infofasta)[[1]])==2) infofasta <- sub(pattern="order=",replacement="",x=infofasta)
  id <- strsplit(infofasta,split=c(" "))[[1]][1]
  infofasta2 <- substr(infofasta,nchar(id)+2,nchar(infofasta))
  infofasta2 <- (strsplit(sub(pattern=";'",replacement="'",x=infofasta2),";"))
  buenos <- unlist(infofasta2)
  buenos <- buenos[grepl("=",buenos)]
  matrix.data <- data.frame(matrix(ncol=2,nrow=length(buenos)))
 
  for (i in 1:length(buenos)) matrix.data[i,] <- strsplit(buenos[i],"=")[[1]]
  rownames(matrix.data) <- gsub("^ ", "", matrix.data$X1)
  if (inicio) {
    db.out <- data.frame(names=c("id",matrix.data$X1,"class_name","phylum_name","kingdom_name",
                               "superkingdom_name","sequence"))
    rownames(db.out) <- c("id",rownames(matrix.data),"class_name","phylum_name","kingdom_name",
                          "superkingdom_name","sequence")
    inicio<-F}
  submatrix.data <- matrix.data$X2[grep(":",matrix.data$X2)]
  dobles <- grep(":",matrix.data$X2)
  for (j in 1:length(submatrix.data)) submatrix.data[j]  <- 
    substr(strsplit(submatrix.data[j],":")[[1]][2],2,nchar(strsplit(submatrix.data[j],":")[[1]][2])-1)
  matrix.data$X2[dobles] <- submatrix.data
  matrix.data["id",2] <- substr(id,1,length_id)
  # matrix.data["seq_length",2] <- db@ranges@width[fila]
  matrix.data["sequence",2] <- as.character(db[fila])

  if (matrix.data["order_name",2]=="None" & matrix.data["family_name",2]=="None" & matrix.data["genus_name",2]!="None"){
    if (matrix.data["genus_name",2] %in% genus_to_family$genus_name){
      matrix.data["family_name",2] <- as.character(genus_to_family$family_name[genus_to_family$genus_name==matrix.data["genus_name",2]])
      matrix.data["order_name",2] <- as.character(family_to_order$order_name[family_to_order$family_name==matrix.data["family_name",2]])} else{
        matrix.data["order_name",2] <- "Correct_manually"
        matrix.data["family_name",2] <- "Correct_manually"
      }
  }
  
    
  if (matrix.data["order_name",2]=="None" & matrix.data["family_name",2]!="None"){
        if (matrix.data["family_name",2] %in% family_to_order$family_name){
        matrix.data["order_name",2] <- as.character(family_to_order$order_name[family_to_order$family_name==matrix.data["family_name",2]])} else{
          matrix.data["order_name",2] <- "Correct_manually"  
        }
  }
  if (length(as.character(taxo_names[taxo_names$order_name==matrix.data["order_name",2],2]))!=0){
    matrix.data["class_name",2] <- as.character(taxo_names[taxo_names$order_name==matrix.data["order_name",2],2])
    matrix.data["phylum_name",2] <- as.character(taxo_names[taxo_names$order_name==matrix.data["order_name",2],3])
    matrix.data["kingdom_name",2] <- as.character(taxo_names[taxo_names$order_name==matrix.data["order_name",2],4])
    matrix.data["superkingdom_name",2] <- as.character(taxo_names[taxo_names$order_name==matrix.data["order_name",2],5])
 } else {
   matrix.data["class_name",2] <- "Correct_manually"
   matrix.data["phylum_name",2] <- "Correct_manually"
   matrix.data["kingdom_name",2] <- "Correct_manually"
   matrix.data["superkingdom_name",2] <- "Correct_manually"
}
if (matrix.data["rank",2]=="phylum" & (length(as.character(phylum_to_sk[phylum_to_sk$phylum_name==matrix.data["scientific_name",2],2]))!=0) ){ 
  matrix.data["phylum_name",2] <- matrix.data["scientific_name",2]
  matrix.data["kingdom_name",2] <- as.character(phylum_to_sk[phylum_to_sk$phylum_name==matrix.data["phylum_name",2],2])
  matrix.data["superkingdom_name",2] <- as.character(phylum_to_sk[phylum_to_sk$phylum_name==matrix.data["phylum_name",2],3])
  
}
if (matrix.data["rank",2]=="class" & (length(as.character(class_to_sk[class_to_sk$class_name==matrix.data["scientific_name",2],2]))!=0) ){ 
  matrix.data["class_name",2] <- matrix.data["scientific_name",2]
  matrix.data["phylum_name",2] <- as.character(class_to_sk[class_to_sk$class_name==matrix.data["class_name",2],2])
  matrix.data["kingdom_name",2] <-as.character(class_to_sk[class_to_sk$class_name==matrix.data["class_name",2],3])
  matrix.data["superkingdom_name",2] <-as.character(class_to_sk[class_to_sk$class_name==matrix.data["class_name",2],4])
}

if (matrix.data["rank",2]=="kingdom" & (length(as.character(kingdom_to_sk[kingdom_to_sk$kingdom_name==matrix.data["scientific_name",2],2]))!=0)){ 
  matrix.data["kingdom_name",2] <- matrix.data["scientific_name",2]
  matrix.data["superkingdom_name",2] <-as.character(kingdom_to_sk[kingdom_to_sk$kingdom_name==matrix.data["kingdom_name",2],2])
}
if (matrix.data["rank",2]=="phylum" & matrix.data["scientific_name",2]=="Phaeophyceae") {
  matrix.data["class_name",2] <- "Phaeophyceae"
  matrix.data["phylum_name",2] <- "Ochrophyta"
  matrix.data["kingdom_name",2] <- "Stramenopiles"
  matrix.data["superkingdom_name",2] <- "Chromalveolata"
  matrix.data["rank",2] <- "class"
}
if (matrix.data["scientific_name",2] %in% exceptions) matrix.data <- fix_exceptions(matrix.data["scientific_name",2])
  

  db.out <- cbind(db.out,row=matrix.data[match(rownames(db.out),rownames(matrix.data)),2])
  if (fila %% showlines == 0) message(fila,"/",length(db)," lines written.","\r",appendLF = FALSE)
 
}
db.outt <- data.frame(t(db.out[-1]))
db.outt$merged_sample <- NULL
reordered_db.outt <- db.outt[,c("id","rank","scientific_name","best_identity",
                                "superkingdom_name","kingdom_name","phylum_name","class_name",
                                "order_name","family_name","genus_name","species_name",
                                "best_match","species_list","taxid","sequence")]

write.table(reordered_db.outt,outfile,row.names=F,col.names=T,sep=";")
message("Output file ",outfile," written with ",length(db), " sequences")
}
